# Generated by Django 2.0.7 on 2018-07-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('md_ctc', '0003_scan_cancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='cancer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
