# Generated by Django 2.0.7 on 2018-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('md_ctc', '0005_auto_20180730_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
