# Generated by Django 2.0.7 on 2018-08-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('md_ctc', '0006_scan_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True),
        ),
    ]
